name: PHP Composer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Socialmedia", "TodoList" ] # List the folders for each project
    steps:
    - uses: actions/checkout@v4

    # Validate composer.json and composer.lock for each project
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      working-directory: ${{ matrix.project }}

    # Cache Composer packages for each project
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ${{ matrix.project }}/vendor
        key: ${{ runner.os }}-php-${{ matrix.project }}-${{ hashFiles('${{ matrix.project }}/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.project }}-

    # Install dependencies for each project
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ${{ matrix.project }}

    # Run test suite for each project (if applicable)
    # Uncomment and adjust the script in composer.json as needed
    # - name: Run test suite
    #   run: composer run-script test
    #   working-directory: ${{ matrix.project }}